sudo: false

language: python

python:
   - "3.5"

services:
   - redis

env:
  - FLASK=0.10.1
  - FLASK=0.9
  - FLASK=0.8.1
  - FLASK=0.7.2

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip install Jinja2
    - pip install Werkzeug
    - pip install itsdangerous 
    - pip install -q Flask==$FLASK
    - pip install -q -r dev_requirements.txt
    - pip install -q -e .

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test