sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:   
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip install Jinja2
    - pip install flask
    - pip install flask-restful
    - pip install flask-sqlalchemy

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test
