sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip3 install flask
    - pip3 install sqlalchemy
    - pip3 install flask_sqlalchemy
    - pip install flask_sqlalchemy
    - pip install flask -f lib
    - pip3 install flask -f lib

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test
