sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip install Flask
    - pip install Jinja2
    - pip install Werkzeug
    - pip install itsdangerous
    - pip install wsgiref
    - pip install Flask-restful 
    - pip install Flask_SQLAlchemy 

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test
