sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install -r app/requirements.txt
    - pip install -t lib -r app/requirements.txt
    - python3 -m pip install -r app/requirements.txt
    - python3 -m pip install lib -r app/requirements.txt
    - pip install flask
    - pip install -t lib flask
    - python3 -m pip install flask
    - python3 -m pip install lib flask
    - pip install flask_sqlalchemy
    - pip install -t lib flask_sqlalchemy
    - python3 -m pip install flask_sqlalchemy
    - python3 -m pip install lib flask_sqlalchemy
    - pip install psycopg2
    - pip install -t lib psycopg2
    - python3 -m pip install psycopg2
    - python3 -m pip install lib psycopg2
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip install Jinja2
    - pip install Werkzeug
    - pip install itsdangerous 

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
#   - make test
