sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip3 install .
    - pip install .
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip3 install --user flask
    - pip3 install --user sqlalchemy
    - pip3 install --user flask_sqlalchemy

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test
