FORMAT: 1A
HOST: magicdb.me

# magicdb.me

Welcome to our Magic: The Gathering API! 
You can use the API to access Magic: The Gathering cards, sets, 
artists, and subtypes.
    
# Group Cards

## Get All Cards [/api/cards]
<code>/api/cards?</code><br>
Retrieves a list of unique card ID's for every card.

### GET Get All Cards [GET]    
+ Response 200 (application/json)
    
        [
            "3cd2261ab8ddf8e9ec0772b5a5208856b5884e75", 
            "43a76d0f78cf3c4ad00600e10175673d4b5a8962", 
            "cb55e0650b80a9df6a6eb2107433758d0ed69eda", 
            "f77ec64e39bdbba73ac83e50230d749b199c0864", 
            "6a47fc5230a71d0e58a03418933639fd661cb272", 
            "175e8a9ed05421b8bcbb8fbc572bfc6c12aed39c", 
            "b5ce58c0017d724ef94340c8b8e7776de8c95720", 
            "fc3dff0b47c4b6d06f386b1c58faab1ee72572d3",
            "...",
            "..."
        ]

## Get a Specific Card [/api/cards/{cardId}]
<code>/api/cards?cardId={id}</code><br>
This endpoint retrieves a specific card by its id.

#### Parameters
- <code>cardId</code> *(string, required)* - getting a specific card by its ID    

+ Parameters
    + cardId: "7cb9b23c2fdee43cadb969a6b61378c6d29f4abf" (string) ID of the card

### GET Get a Specific Card [GET]    
+ Response 200 (application/json)
        
        {
              "art": "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=426070&type=card", 
              "artist": "Volkan Baga", 
              "cardId": "fc3dff0b47c4b6d06f386b1c58faab1ee72572d3", 
              "color": "none", 
              "expansionSet": "MM3", 
              "mainType": "Land", 
              "manaCost": null, 
              "name": "Seaside Citadel", 
              "power": "none", 
              "rarity": "Uncommon", 
              "subType": [
                "none"
              ], 
              "text": "Seaside Citadel enters the battlefield tapped.\n{T}: Add {G}, {W}, or {U} to your mana pool.", 
              "toughness": "none"
        }


# Group Sets

## Get All Sets [/api/sets]
<code>/api/sets?</code><br>

Retrieves list of set codes for all sets.

### GET Get All Sets [GET]    
+ Response 200 (application/json)
        
        [  
          "EMN", 
          "V16", 
          "CN2", 
          "DDR", 
          "KLD", 
          "MPS", 
          "C16", 
          "PCA", 
          "AER", 
          "MM3", 
          "...", 
          "..."
        ]

## Get a Specific Set [/api/sets/{code}]
<code>/api/sets/?code={code}</code><br>
This endpoint retrieves a specific set by its set code.

#### Parameters
- <code>code</code> *(string, required)* - get a specific set by its set code

+ Parameters
    + code: 12345 (string) set code

### GET Get a Specific Set [GET]    
+ Response 200 (application/json)
    
        {
          "artists": [
            "Michael Whelan"
          ], 
          "block": "none", 
          "cards": [
            "2f6ad2b7730247c9eb7acc83abc33bb6fe569749"
          ], 
          "code": "pDRC", 
          "name": "Dragon Con", 
          "numCards": 1, 
          "rDate": "1994-01-01", 
          "subTypes": [
            "Dragon"
          ], 
          "symbol": "https://tournamentcenter.eu/sites/default/files/mtg-logo.png"
        }

# Group Subtypes

## Get All Subtypes [/api/subtypes]
<code>/api/subtypes?</code><br>
Retrieves a list of all card subtypes

### GET Get All Subtypes [GET]    
+ Response 200 (application/json)
    
        [  
          {
            "cards": [], 
            "name": "Nestor", 
            "numCards": 5, 
            "numSets": null, 
            "sets": []
          }, 
          {
            "cards": [], 
            "name": "Nic", 
            "numCards": 2, 
            "numSets": null, 
            "sets": []
          }, 
          {
            "cards": [], 
            "name": "Nilo", 
            "numCards": 1, 
            "numSets": null, 
            "sets": []
          }, 
          {
            "cards": [], 
            "name": "Joel", 
            "numCards": 6, 
            "numSets": null, 
            "sets": []
          }, 
          {...},
          {...}
        ]


# Group Artists

## Get All Artists [/api/artists]
<code>/api/artists?</code><br>
Retrieves a list all card artists

### GET Get All Artists [GET]     
+ Response 200 (application/json)
    
        [  
          {
            "cards": [
              "00fcbc5eaa2fe77d9726c274ef40daa7bf8293df", 
              "a6097658f1cda44a19551ae62773edaea0567f8d", 
              "4004d40826e08e15e6722faf930a807c5207899d", 
              "6b3427be0ada96f9aed8f6dcc8dbe445a9a3b80f", 
              "a12af247be2c14d38a0c8297b12604c9aa89f086", 
              "26993fce91f42e5747c238c2902c300fed27a1cc", 
              "0c0e950a98d07746a1d0741837e6808392b980f1", 
              "0c030ebdc1ee2c7799c77bfd33de3016e510ebfc", 
              "25a650f113a98e0ebcfe031a99ca952e9777ae27", 
              "128500ada95d35b3879d9070bd0acb6518ba1236", 
              "3009694702f9f208d60d15469c41a116f622a9ae", 
              "47695a6cec8f658d2f1ed79d7fad591e36a78e1d", 
              "07a1d95a94cb68e078ccb285941f5504cefe2bc5", 
              "03a88a994fc8b096529330d10dc360f627e12c74", 
              "7686fcfa5ad4321c123d3486f04031318c1f72c9", 
              "0e47c4f3fb988889ec9c462c08c545d7436beb28", 
              "1069f0e23bb0f502b4bc305c72c6a7f75e51bc8f", 
              "bef6b032ac8517ef2ffab94a66aab110fa3b2925", 
              "56d8e1601a5ca6e3f4f7256d0112d9f9d72e0c3b", 
              "35cdc15ee92161572bfceb349ec1a981d4d44d64"
            ], 
            "name": "George Pratt", 
            "numCards": 20, 
            "numSets": 7, 
            "sets": [
              "VIS", 
              "5ED", 
              "WTH", 
              "6ED", 
              "MMQ", 
              "BRB", 
              "BTD"
            ]
          },
          {...},
          {...}
        ]