runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config: 
  python_version: 3.5


beta_settings:
    cloud_sql_instances: tutorial-project-161522:us-central1:magicinstance

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
